apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: deeplog
  labels:
    app: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: asia-northeast3-docker.pkg.dev/pro-platform-495513-b9/deeplog-repo/log-generator:052f59d6374328b8db321489f1b05450558ff6cc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-cluster-kafka-bootstrap.deeplog.svc:9092"
        - name: KAFKA_TOPIC
          value: "hdfs-raw-logs"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: log-generator-service
  namespace: deeplog
spec:
  selector:
    app: log-generator
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
