apiVersion: v1
kind: ServiceAccount
metadata:
  name: deeplog-model-reader
  namespace: deeplog
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    iam.gke.io/gcp-service-account: github-action@pro-platform-495513-b9.iam.gserviceaccount.com
