apiVersion: v1
kind: ServiceAccount
metadata:
  name: deeplog-model-reader
  namespace: deeplog
  annotations:
    iam.gke.io/gcp-service-account: deeplog-model-reader@pro-platform-495513-b9.iam.gserviceaccount.com
